# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0002_auto_20171030_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaocontratante',
            options={'ordering': ['contratante', 'profissional'], 'verbose_name_plural': 'Avaliação Contratantes'},
        ),
        migrations.AlterModelOptions(
            name='avaliacaoprofissional',
            options={'ordering': ['profissional', 'contratante'], 'verbose_name_plural': 'Avaliação Profissionais'},
        ),
    ]
