# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0003_auto_20171030_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratante',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_profissional'),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='orgao_expeditor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='rg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_profissional'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='orgao_expeditor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='rg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
