# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0006_auto_20171101_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(default='Sem comentários'),
        ),
    ]
