# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0007_auto_20171101_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoprofissional',
            name='data_servico',
            field=models.DateField(auto_now_add=True, default='2017-11-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacaoprofissional',
            name='servico',
            field=models.CharField(max_length=255),
        ),
    ]
