# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0009_auto_20171104_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoprofissional',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
