# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0010_auto_20171104_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoprofissional',
            name='contratante',
            field=models.IntegerField(),
        ),
    ]
