# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0014_userprofile_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('Usuário', 'Usuário'), ('Profissional', 'Profissional')], default='Usuário', max_length=20),
        ),
    ]
