# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0015_userprofile_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2017-11-13 12:00:00'),
            preserve_default=False,
        ),
    ]
