# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratou', '0016_profissionalquestion_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissionalquestion',
            options={'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profissional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratou.Profissional'),
        ),
    ]
